stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

services:
  - name: docker:20.10.12-dind
    alias: docker

build:
  stage: build
  tags:
    - ci.inria.fr
    - small
  image: docker:20.10
  script:
    - docker-compose up -d
    - docker images
    - docker ps -a
    - docker run --network container:backend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
    - cat /proc/1/cgroup # check the CGroup
