version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - './backend:/opt/app'
    ports:
      - '5000:5000'

  bdd:
    container_name: redis
    image: "redis:alpine"
